//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedCDripLogChecker.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lists() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomatedCDripLogChecker.Core.Lists", typeof(Lists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Игнориране името на файла
        ///50 =&gt; Недопустима стойност !
        ///51 =&gt; Невалидни символи !
        ///52 =&gt; Невалидно име на файл !
        ///1200 =&gt; Отчет за състояние и грешки
        ///2501 =&gt; Състояние и грешки на трак
        ///1203 =&gt; Възможни Грешки
        ///1204 =&gt; Създай Отчет
        ///1210 =&gt; Състояние и грешки на диапазон
        ///1211 =&gt; Избран диапазон
        ///1212 =&gt;      Синхронизационен проблем 
        ///1213 =&gt;      Подозрително местоположение 
        ///1214 =&gt;      Липсващи семпли
        ///1215 =&gt;      Твърде много семпли
        ///1216 =&gt;      Грешка при запис на файл
        ///1217 =&gt;      Пиково  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Název souboru bude ignorován
        ///50 =&gt; Hodnota je mimo rozsah!
        ///51 =&gt; Neplatné znaky!
        ///52 =&gt; Neplatný název souboru!
        ///1200 =&gt; Stavová a chybová hlášení
        ///2501 =&gt; Stopa - stav a chyby
        ///1203 =&gt; Možné chyby
        ///1204 =&gt; Vytvořit protokol
        ///1210 =&gt; Rozsah - stav a chyby
        ///1211 =&gt; Vybraný rozsah
        ///1212 =&gt;      problém s časováním 
        ///1213 =&gt;      podezřelá pozice 
        ///1214 =&gt;      chybějící vzorky
        ///1215 =&gt;      příliš mnoho vzorků
        ///1216 =&gt;      chyba zápisu souboru
        ///1217 =&gt;      špičková úroveň 
        ///1299 =&gt;      rychlost ext [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Dateiname wird ignoriert
        ///50 =&gt; Wert außerhalb des Bereichs !
        ///51 =&gt; Ungültige Zeichen !
        ///52 =&gt; Ungültiger Dateiname !
        ///1200 =&gt; Status und Fehlermeldungen
        ///2501 =&gt; Track Status und Fehler
        ///1203 =&gt; Mögliche Fehler
        ///1204 =&gt; Erzeuge Log
        ///1210 =&gt; Bereichsstatus und Fehler
        ///1211 =&gt; Gewählter Bereich
        ///1212 =&gt;      Timing Problem 
        ///1213 =&gt;      Verdächtige Position 
        ///1214 =&gt;      Fehlende Samples
        ///1215 =&gt;      Zu viele Samples
        ///1216 =&gt;      Datei Schreibfehler
        ///1217 =&gt;      Spitzenpegel 
        ///1299 =&gt;      Ausles [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 16X12 DVD DUAL,91
        ///- 16X16 DVD DUAL,91    
        ///- 16X52X32X52COMBO,738    
        ///- 16X8 DVD DUAL,91    
        ///- 24X10X40 CD-RW,97    
        ///- 32X12X48 CD-RW,97    
        ///- 36X CD-ROM,12    
        ///- 40X CD-ROM,12    
        ///- 40X12X48 CD-RW,97    
        ///- 48X12X50 CD-RW,97    
        ///- 52X CD-ROM,12    
        ///- 52X24X52 CD-RW,97    
        ///- 52X32COMBO,738    
        ///- 52X32X52 CD-RW,97    
        ///- 52X32XCOMBO,738    
        ///- 54X CD-ROM,12    
        ///- 56X CD-ROM,12    
        ///- ATAPI CDROM 48X,691    
        ///- ATAPI CDROM 52X,691    
        ///- ATAPI CDROM.40X,12    
        ///- ATAPI CDROM.48X,12    
        ///- ATAPI  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DriveDB {
            get {
                return ResourceManager.GetString("DriveDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Filename will be ignored,
        ///50 =&gt; Value out of range !,
        ///51 =&gt; Invalid characters !,
        ///52 =&gt; Invalid filename !,
        ///1200 =&gt; Status and Error Messages,
        ///2501 =&gt; Track status and errors,
        ///1203 =&gt; Possible Errors,
        ///1204 =&gt; Create Log,
        ///1210 =&gt; Range status and errors,
        ///1211 =&gt; Selected range,
        ///1212 =&gt;  Timing problem ,
        ///1213 =&gt;  Suspicious position ,
        ///1214 =&gt;  Missing samples,
        ///1215 =&gt;  Too many samples,
        ///1216 =&gt;  File write error,
        ///1217 =&gt;  Peak level ,
        ///1299 =&gt;  Extraction speed ,
        ///1218 =&gt;  Range quality , [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; El nombre del archivo será ignorado
        ///50 =&gt; Valor fuera del rango !
        ///51 =&gt; Caracteres inválidos !
        ///52 =&gt; Nombre de archivo inválido !
        ///1200 =&gt; Mensajes de Error y Estado
        ///2501 =&gt; Anotar estado y errores
        ///1203 =&gt; Errores posibles
        ///1204 =&gt; Crear Log
        ///1210 =&gt; Gama de estados y errores
        ///1211 =&gt; Seleccionar gama
        ///1212 =&gt;      Problema de Sincronización 
        ///1213 =&gt;      Posición Sospechosa 
        ///1214 =&gt;      Muestras desaparecidas
        ///1215 =&gt;      Demasiadas Muestras
        ///1216 =&gt;      Error de Escritura en Archivo
        ///1217  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Les Noms de Fichiers seront ignorés
        ///50 =&gt; Valeur hors de portée !
        ///51 =&gt; Caractères invalides !
        ///52 =&gt; Nom de fichier invalide !
        ///1200 =&gt; Messages d&apos;État et d&apos;Erreur
        ///2501 =&gt; États et Erreurs Piste
        ///1203 =&gt; Erreurs possibles
        ///1204 =&gt; Créer un journal
        ///1210 =&gt; Propriétés États et Erreurs
        ///1211 =&gt; Gammes sélectionnées
        ///1212 =&gt;      problème calcul 
        ///1213 =&gt;      position suspecte 
        ///1214 =&gt;      samples manquants
        ///1215 =&gt;      Trop de samples
        ///1216 =&gt;      erreur d&apos;écriture fichier
        ///1217 =&gt;      Niveau  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Il nome del file sarà ignorato
        ///50 =&gt; Valore fuori dall&apos;intervallo!
        ///51 =&gt; Caratteri non validi!
        ///52 =&gt; Nome del file non valido!
        ///1200 =&gt; Messaggi di stato e di errore
        ///2501 =&gt; Stato traccia ed errori
        ///1203 =&gt; Errori Possibili
        ///1204 =&gt; Crea Log
        ///1210 =&gt; Stato intervallo ed errori
        ///1211 =&gt; Intervallo selezionato
        ///1212 =&gt;      Problema di timing 
        ///1213 =&gt;      Posizione sospetta 
        ///1214 =&gt;      Sample mancanti
        ///1215 =&gt;      Troppi sample
        ///1216 =&gt;      Errore di scrittura file
        ///1217 =&gt;      Livello di pi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; 指定されたファイル名は無視されます
        ///50 =&gt; 範囲外です !
        ///51 =&gt; 無効な文字です !
        ///52 =&gt; 無効なファイル名です !
        ///1200 =&gt; ステータスとエラー メッセージ
        ///2501 =&gt; トラックステータスとエラー
        ///1203 =&gt; 考えられるエラー
        ///1204 =&gt; ログ作成
        ///1210 =&gt; 展開範囲ステータスとエラー
        ///1211 =&gt; 選択された範囲
        ///1212 =&gt;      タイミングプロブレム 
        ///1213 =&gt;      疑わしい位置 
        ///1214 =&gt;      消失サンプル
        ///1215 =&gt;      過剰サンプル
        ///1216 =&gt;      ファイル書き込みエラー
        ///1217 =&gt;      ピークレベル 
        ///1218 =&gt;      選択範囲品質 
        ///1219 =&gt;      CRC 
        ///1220 =&gt;      コピー OK
        ///1221 =&gt;      コピー完了
        ///1227 =&gt;      トラック品質 
        ///1228 =&gt;      コピー中止
        ///1269 =&gt;      ファイル名 
        ///1270 =&gt;      プリギャップ長 
        ///1271 =&gt;   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; 指定されたファイル名は無視されます
        ///50 =&gt; 範囲外です !
        ///51 =&gt; 無効な文字です !
        ///52 =&gt; 無効なファイル名です !
        ///1200 =&gt; ステータスとエラー メッセージ
        ///2501 =&gt; トラックステータスとエラー
        ///1203 =&gt; 考えられるエラー
        ///1204 =&gt; ログ作成
        ///1210 =&gt; 範囲取り込みステータス &amp; エラー
        ///1211 =&gt; 選択された範囲
        ///1212 =&gt;      タイミングプロブレム 
        ///1213 =&gt;      疑わしい位置 
        ///1214 =&gt;      消失サンプル
        ///1215 =&gt;      過剰サンプル
        ///1216 =&gt;      ファイル書き込みエラー
        ///1217 =&gt;      ピークレベル 
        ///1299 =&gt;      範囲取り込み品質 
        ///1218 =&gt;      選択範囲品質 
        ///1219 =&gt;      CRC 
        ///1220 =&gt;      コピー OK
        ///1221 =&gt;      コピー完了
        ///1227 =&gt;      トラック品質 
        ///1228 =&gt;      コピー中止
        ///1269 =&gt;      ファイル名 
        ///1270 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JP99 {
            get {
                return ResourceManager.GetString("JP99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Bestands naam wordt genegeerd
        ///50 =&gt; Waarde buiten bereik!
        ///51 =&gt; Ongeldig teken!
        ///52 =&gt; Ongeldige bestands naam!
        ///1200 =&gt; Status en Foutmeldingen
        ///2501 =&gt; Track status en fouten
        ///1203 =&gt; Mogelijke Fouten
        ///1204 =&gt; Log Aanmaken
        ///1210 =&gt; Bereikstatus en fouten
        ///1211 =&gt; Geselecteerd bereik
        ///1212 =&gt;      Timing probleem 
        ///1213 =&gt;      Twijfelachtige positie 
        ///1214 =&gt;      Ontbrekende samples
        ///1215 =&gt;      Te veel samples
        ///1216 =&gt;      Bestand schrijffout
        ///1217 =&gt;      Piek niveau 
        ///1299 =&gt;      Uitlees sn [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Nazwa pliku będzie ignorowana
        ///50 =&gt; Wartość poza zakresem!
        ///51 =&gt; Nieprawidłowy znak!
        ///52 =&gt; Nieprawidłowa nazwa pliku!
        ///1200 =&gt; Komunikaty błędów i stanu
        ///2501 =&gt; Stan i błędy nagrań
        ///1203 =&gt; Możliwe błędy
        ///1204 =&gt; Zapisz raport
        ///1210 =&gt; Stan i błędy zakresu
        ///1211 =&gt; Wybrany zakres
        ///1212 =&gt;      Problem z taktowaniem 
        ///1213 =&gt;      Podejrzane miejsce 
        ///1214 =&gt;      Brakuje próbek 
        ///1215 =&gt;      Za dużo próbek 
        ///1216 =&gt;      Błąd zapisu pliku 
        ///1217 =&gt;      Poziom wysterowania 
        ///1299 =&gt;      Szybkość [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Имя файла игнорируется
        ///50 =&gt; Значение вне диапазона.
        ///51 =&gt; Недопустимые символы.
        ///52 =&gt; Недопустимое имя файла.
        ///1200 =&gt; Информационное окно
        ///2501 =&gt; Характеристики треков и сообщения об ошибках
        ///1203 =&gt; Возможные ошибки
        ///1204 =&gt; Создать отчёт
        ///1210 =&gt; Характеристики диапазона извлечения и сообщения об ошибках
        ///1211 =&gt; Выбранный диапазон
        ///1212 =&gt;      Проблемы синхронизации 
        ///1213 =&gt;      Подозрительная позиция 
        ///1214 =&gt;      Пропущены сэмплы
        ///1215 =&gt;      Слишком много сэмплов
        ///1216 =&gt;      Ошибка  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Filename will be ignored
        ///50 =&gt; Value out of range !
        ///51 =&gt; Invalid characters !
        ///52 =&gt; Invalid filename !
        ///1200 =&gt; Status and Error Messages
        ///2501 =&gt; Track status and errors
        ///1203 =&gt; Possible Errors
        ///1204 =&gt; Create Log
        ///1210 =&gt; Range status and errors
        ///1211 =&gt; Selected range
        ///1212 =&gt;      Timing problem 
        ///1213 =&gt;      Suspicious position 
        ///1214 =&gt;      Missing samples
        ///1215 =&gt;      Too many samples
        ///1216 =&gt;      File write error
        ///1217 =&gt;      Peak-nivĺ 
        ///1299 =&gt;      Extraction speed 
        ///1218 =&gt;      R [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Názov súboru bude ignorovaný
        ///50 =&gt; Hodnota je mimo rozsah !
        ///51 =&gt; Nesprávne znaky !
        ///52 =&gt; Neplatný názov súboru !
        ///1200 =&gt; Správy o stave a chybách
        ///2501 =&gt; Stav a chyby stopy
        ///1203 =&gt; Možné chyby
        ///1204 =&gt; Vytvoriť log
        ///1210 =&gt; Stav a chyby rozsahu
        ///1211 =&gt; Vybraný rozsah
        ///1212 =&gt;      Časový problém 
        ///1213 =&gt;      Podozrivá pozícia 
        ///1214 =&gt;      Chýbajúce vzorky
        ///1215 =&gt;      Príliš veľa vzoriek
        ///1216 =&gt;      Chyba zápisu súboru
        ///1217 =&gt;      Špičková úroveň 
        ///1299 =&gt;      Rýchlosť extrakcie 
        ///12 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Ime datoteke se ignoriše
        ///50 =&gt; Vrednost van opsega !
        ///51 =&gt; Nedozvoljeni karakteri !
        ///52 =&gt; Nedozvoljeno ime datoteke !
        ///1200 =&gt; Statusne i poruke o greškama
        ///2501 =&gt; Track status i greške
        ///1203 =&gt; Moguće greške
        ///1204 =&gt; Kreiraj dnevnik
        ///1210 =&gt; Status i greške opsega
        ///1211 =&gt; Izabrani opseg
        ///1212 =&gt;      Problem u tajmingu 
        ///1213 =&gt;      Sumnjiva pozicija 
        ///1214 =&gt;      Nedostaju semplovi
        ///1215 =&gt;      Previše semplova
        ///1216 =&gt;      Greška pri snimanju fajla
        ///1217 =&gt;      Vršni nivo 
        ///1299 =&gt;      B [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; Filnamnet kommer att ignoreras
        ///50 =&gt; Värdet är utom valt område !
        ///51 =&gt; Felaktiga tecken !
        ///52 =&gt; Felaktigt filnamn !
        ///1200 =&gt; Status och Fel Meddelanden
        ///2501 =&gt; Spårstatus och fel
        ///1203 =&gt; Möjliga fel
        ///1204 =&gt; Skapa Logg
        ///1210 =&gt; Områdets status och fel
        ///1211 =&gt; Utvalt område
        ///1212 =&gt;      Timing-problem 
        ///1213 =&gt;      Misstänkt position 
        ///1214 =&gt;      Saknade samplingar
        ///1215 =&gt;      För många samplingar
        ///1216 =&gt;      Fil-skrivfel
        ///1217 =&gt;      Peak-nivå 
        ///1299 =&gt;      Extraheringshastighet 
        ///121 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 31 =&gt; 文件名将被忽略
        ///50 =&gt; 超出数值范围！
        ///51 =&gt; 无效的字符！
        ///52 =&gt; 无效的文件名！
        ///1200 =&gt; 状态及错误信息
        ///2501 =&gt; 音轨状态及错误
        ///1203 =&gt; 可能的错误
        ///1204 =&gt; 创建日志
        ///1210 =&gt; 范围状态及错误
        ///1211 =&gt; 已选择范围
        ///1212 =&gt;      计时问题 
        ///1213 =&gt;      可疑位置 
        ///1214 =&gt;      缺失采样
        ///1215 =&gt;      过多采样
        ///1216 =&gt;      文件写入错误
        ///1217 =&gt;      峰值电平 
        ///1299 =&gt;      抓取速度 
        ///1218 =&gt;      范围质量 
        ///1219 =&gt;      CRC 
        ///1220 =&gt;      复制成功
        ///1221 =&gt;      复制结束
        ///1227 =&gt;      音轨质量 
        ///1228 =&gt;      复制被中止
        ///1269 =&gt;      文件名 
        ///1270 =&gt;      前间隙长度 
        ///1271 =&gt;      测试 CRC 
        ///1272 =&gt;      复制 CRC 
        ///1273 =&gt;      正在压缩        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ZH {
            get {
                return ResourceManager.GetString("ZH", resourceCulture);
            }
        }
    }
}
